- name: "Run Play"
  hosts: all
  gather_facts: false
  tasks:
  - name: "Task 1: Lista as variáveis recebidas"
    debug:
      msg: "Variaveis: efs_mount_point: {{ efs_mount_point }}; user_dir: {{ user_dir }}; cifar_data_dir: {{ cifar_data_dir }}; master_hostname: {{ master_hostname }}"
